branch-defaults:
  release/prod:
    environment: mail-prod
  release/test:
    environment: mail-test
global:
  application_name: mail
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  profile: eb-cli
  sc: git
